default: &default
  adapter: postgresql
  user: postgres
  password: postgres
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: ledxchange_development

test:
  <<: *default
  database: ledxchange_test